config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new,:create]
    resources :reviews, only: :create

  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :list_id, uniqueness: {
     scope: :movie_id
    }

  # validates :comment, presence: true, numericality: { less_than_or_equal_to: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @post = Date.today
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def delete
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, notice: 'List was successfully deleted.'
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/bookmarks/new.html.erb
<%= render 'shared/navbar' %>
<div class="card">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit 'Create my bookmark', class: 'btn btn-info mt-2' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <h1>My libraries:</h1>
</div>
<div class="container">
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path('image_logo_03') %>)">
        <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  </div>
</div>
<div class="container">
</div>

app/views/lists/new.html.erb
<%= render 'shared/navbar' %>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'List Name' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%= render 'shared/navbar' %>
<div class="container mt-3">
  <h1><%=@list.name%></h1>
</div>
<div class="container">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit 'Create my bookmark', class: 'btn btn-info mt-2' %>
  <% end %>
</div>
</div>
<div class="container mt-3">
  <div class="row mt-4">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-md-4 mb-3">
        <div class="card h-100">
          <%= cl_image_tag @article.photo.key, height: 300, width: 400, crop: :fill, class: "card-img-top", alt: "#{bookmark.movie.title} poster" %>
          <div class="card-body">
            <h5 class="card-title"><%= bookmark.movie.title %></h5>
            <p class="card-text"><%= bookmark.movie.overview %></p>
            <p class="card-text"><strong>Rating:</strong> <%= bookmark.movie.rating %></p>
            <div class="card-text">
              <% @list.bookmarks.each do |bookmark| %>
                <p>Personal comment:<br>
                  <em>"<%=bookmark.comment%>"</em><br>
                  <small><%=@post.strftime(":posted on %d/%m/%y")%></small>
                </p>
              <%end%>
              <%= button_to 'Delete', bookmark_path(bookmark), method: :delete, class: 'btn btn-danger mt-2', data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%# <%= link_to "Delete this list", list_path(@list), class: "btn btn-danger mt-4", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
    <ul class="navbar-nav d-flex justify-content-center">
      <li class="nav-item active">
        <%= link_to "Home", lists_path(@lists), class: "btn btn-ghost m-2" %>
      </li>
      <li class="nav-item active">
        <%= link_to "New list", new_list_path, class: "btn btn-ghost m-2" %>
      </li>
    </ul>
  </div>
</div>